name: kratom_dosage_calculator
description: Calculates kratom dosage based on weight, desired effects and 

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api_com:
    git:
      url: https://github.com/CreevekCZ/api_com
      ref: devel
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^6.5.2
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.0
  palestine_console: ^0.0.10
  riverpod_annotation: ^2.0.4
  uuid: ^3.0.7

dev_dependencies:
  analyzer: ^5.4.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  hive_test: ^1.0.1
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.4

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon.png"
  min_sdk_android: 21
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

